### ISSUE TITLE
InvalidScopeError when using custom Scope in Field

### ISSUE THREAD

**Issue by mickmuzac** [openedx/XBlock#239]
This is the code I'm currently using to try to do this:

``` python
tableStructure = Dict(default={}, scope=Scope(UserScope.NONE, BlockScope.TYPE), help="Help Text")
```

Whenever I attempt to read the value of the Field, an `InvalidScopeError` is raised. This doesn't seem to happen with the other predefined Scopes (e.g `Scope.content`). Furthermore, the error only seems to happen if I attempt to access the value of the Field from within the student_view.

Here is a stack trace:

```
2014-09-10 10:15:13,883 WARNING 2366 [contentstore.views.preview] preview.py:223 - Unable to render student_view for <TableXBlockWithMixins @4644 rerandomize='never', graded=False, annotation_token_secret='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', giturl=None, source_file=None, course_edit_method='Studio', default_tab=None, showanswer='finished', display_name='Table XBlock', video_speed_optimizations=True, chrome=None, showColumns=[], due=None, start=datetime.datetime(2030, 1, 1, 0, 0, tzinfo=<UTC>), tags=[], days_early_for_beta=None, max_attempts=None, text_customization={}, userRows={}, parent=None, format=None, matlab_api_key=None, xqa_key=None, annotation_storage_url='http://your_annotation_storage.com', use_latex_compiler=False, extended_due=None, static_asset_path='', hide_from_toc=False, count=0, name=None, ispublic=None, user_partitions=[], graceperiod=None, visible_to_staff_only=False, tableStructure=???>
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 221, in get_preview_fragment
    fragment = module.render(preview_view, context)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/core.py", line 289, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1166, in render
    return block.xmodule_runtime.render(to_render, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1029, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 586, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/Table-XBlock/table/table.py", line 68, in student_view
    tab = self.tableStructure
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/fields.py", line 369, in __get__
    if xblock._field_data.has(xblock, self.name):
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/field_data.py", line 174, in has
    return self._field_data(block, name).has(block, name)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/field_data.py", line 153, in _field_data
    raise InvalidScopeError(scope)
InvalidScopeError: ScopeBase(user=UserScope.NONE, block=BlockScope.TYPE, name=u'UserScope.NONE_BlockScope.TYPE')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 810, in emit
    self.socket.sendto(msg, self.address)
TypeError: getsockaddrarg: AF_INET address must be tuple, not NoneType
Logged from file preview.py, line 223
[10/Sep/2014 10:15:13] "GET /xblock/i4x://ADL/ADL101/table/ac25938d0f7941878430fbf40c501747/student_view?_=1410358513743 HTTP/1.1" 200 1686
```

**Comment by geoff-va** [comment]
I was trying to do the exact same thing you were. It doesn't appear as if custom Scopes are supported (or I just can't figure out how to implement them).

There is an `LmsFieldData`  class in `edx-platform/lms/djangoapps/lms_xblock/field_data.py` that inherits from `SplitFieldData` (Xblock `field_data.py`). In the the `LmsFieldData` constructor, it lists the 'allowable' scopes. eg:

```python
        super(LmsFieldData, self).__init__({
            Scope.content: authored_data,
            Scope.settings: authored_data,
            Scope.parent: authored_data,
            Scope.children: authored_data,
            Scope.user_state_summary: student_data,
            Scope.user_state: student_data,
            Scope.user_info: student_data,
            Scope.preferences: student_data,
        })
```

I can't find a way to register a new one.

Does anyone know if custom scopes are supported in any way? The documentation isn't clear, but seems to suggest it's possible by explaining all the different combinations and pointing our 'here are some predefined ones'.

Thanks!
